### PR TITLE
Feature: Tune of the month

### PR DESCRIPTION
**Pull request by tobyspark**
Adds competitions to The Machine Folk Session. The idea is for the community to select a tune, learn it, and upload recordings of their performances of it. Could be a 'tune of the month' feature.

A competition is created by an administrator, who writes an introduction and selects a number of candidate tunes. The page can then go live, and there are three following stages:
- Voting to select the tune
- Submission of performances
- Voting for the winning performance (optional)

Each competition has a discussion thread, and the winning tune and all performances are shown after the competition has finished.

### CODE REVIEW

**Comment by tobyspark** [comment]
- [ ] competitions page that isn't just all competitions concatenated
- [ ] handle timezones given cut-offs are in UTC date boundaries
- [ ] add 'featured in competition' to tune, recording pages
- [ ] choose settings as well as tunes

**Comment by boblsturm** [comment]
It shouldn't be a competition, but a community exercise really. Voting is just for "What tune should we all try to learn together this month?" Everyone submitting will be a winner in my view! :)

**Comment by tobyspark** [comment]
Ya. The community exercise thing is not lost on me. This should have all the functionality for that, and more. And the noun used on the public site can be anything.

And, ah, /competitions with a competition that has finished no longer errors out.

**Comment by tobyspark** [comment]
You can now leave the dates for recording vote open+close blank, and if so there will no hint that voting on the recordings could be a thing.

**Comment by tobyspark** [comment]
- [ ] Remove 'performance submission' meta entirely if no performance voting
- [ ] melodeon text tweak
- [ ] hide search for now

**Comment by tobyspark** [comment]
@boblsturm Deployed, still without being linked-to from the main menu

**Comment by tobyspark** [comment]
@boblsturm Deployed, period.

**Pull request merged**
